version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      - mongodb
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - backend

  telegram-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: telegram-bot
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - backend

networks:
  backend:
    driver: bridge